
backend:
  name: github
  repo: salemaziel/food-demo02-netlifycms
  branch: master
media_folder: static/assets/images
public_folder: /assets
collections:
  - name: Personalization
    label: Personalization
    files:
      - label: "Change Logos, Background Photos, Page Titles, and Links"
        name: "customization"
        file: "site/customization.yml"
        fields:
          - {label: "Logo Image", name: "logo-image", widget: image}
          - {label: "Background Photo", name: "background-photo", widget: image}
          - {label: "Site Title", name: "site-title", widget: string}
          - {label: "Site Subtitle", name: "site-subtitle", widget: string}
          - {label: "Business Address", name: "business-address", widget: string}
          - {label: "Business Phone", name: "business-phone", widget: string}
          - {label: "Sunday Hours", name: "sunday-hours", widget: string}
          - {label: "Monday Hours", name: "monday-hours", widget: string}
          - {label: "Tuesday Hours", name: "tuesday-hours", widget: string}
          - {label: "Wednesday Hours", name: "wednesday-hours", widget: string}
          - {label: "Thursday Hours", name: "thursday-hours", widget: string}
          - {label: "Friday Hours", name: "friday-hours", widget: string}
          - {label: "Saturday Hours", name: "saturday-hours", widget: string}
          - {label: "Facebook link", name: "facebook-link", widget: string}
          - {label: "Instagram link", name: "instagram-link", widget: string}
          - {label: "Twitter link", name: "twitter-link", widget: string}
          - {label: "Yelp link", name: "yelp-link", widget: string}




          